/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#ifndef DECT_RPC_IDS_H_
#define DECT_RPC_IDS_H_

/** @brief Command IDs sent from client to server (server handles these) */
enum dect_rpc_cmd_server {
	DECT_RPC_CMD_ACTIVATE = 0,
	DECT_RPC_CMD_DEACTIVATE,
	DECT_RPC_CMD_RSSI_SCAN,
	DECT_RPC_CMD_SCAN,
	DECT_RPC_CMD_ASSOCIATION_REQ,
	DECT_RPC_CMD_ASSOCIATION_RELEASE,
	DECT_RPC_CMD_CLUSTER_START,
	DECT_RPC_CMD_CLUSTER_RECONFIGURE,
	DECT_RPC_CMD_CLUSTER_STOP,
	DECT_RPC_CMD_NW_BEACON_START,
	DECT_RPC_CMD_NW_BEACON_STOP,
	DECT_RPC_CMD_NETWORK_CREATE,
	DECT_RPC_CMD_NETWORK_REMOVE,
	DECT_RPC_CMD_NETWORK_JOIN,
	DECT_RPC_CMD_NETWORK_UNJOIN,
	DECT_RPC_CMD_SETTINGS_READ,
	DECT_RPC_CMD_SETTINGS_WRITE,
	DECT_RPC_CMD_STATUS_INFO_GET,
	DECT_RPC_CMD_NEIGHBOR_LIST,
	DECT_RPC_CMD_NEIGHBOR_INFO,
	DECT_RPC_CMD_CLUSTER_INFO,
	DECT_RPC_CMD_EVENT_SUBSCRIBE,
};

/** @brief Event IDs sent from server to client (client handles these) */
enum dect_rpc_cmd_client {
	DECT_RPC_EVT_ACTIVATE_DONE = 0,
	DECT_RPC_EVT_DEACTIVATE_DONE,
	DECT_RPC_EVT_RSSI_SCAN_RESULT,
	DECT_RPC_EVT_RSSI_SCAN_DONE,
	DECT_RPC_EVT_SCAN_RESULT,
	DECT_RPC_EVT_SCAN_DONE,
	DECT_RPC_EVT_ASSOCIATION_CHANGED,
	DECT_RPC_EVT_NETWORK_STATUS,
	DECT_RPC_EVT_SINK_STATUS,
	DECT_RPC_EVT_CLUSTER_CREATED_RESULT,
	DECT_RPC_EVT_CLUSTER_STOPPED_RESULT,
	DECT_RPC_EVT_NW_BEACON_START_RESULT,
	DECT_RPC_EVT_NW_BEACON_STOP_RESULT,
	DECT_RPC_EVT_NEIGHBOR_LIST,
	DECT_RPC_EVT_NEIGHBOR_INFO,
	DECT_RPC_EVT_CLUSTER_INFO,
};

#endif /* DECT_RPC_IDS_H_ */

