# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Phytec link_board_eth (ENC424J600) Ethernet shield on nRF9151 DK.
# Devicetree: Zephyr shield zephyr/boards/shields/link_board_eth/link_board_eth.overlay
#
# Build:
#   west build -b nrf9151dk/nrf9151/ns <this_sample> -- \
#     -DSHIELD=link_board_eth \
#     -DEXTRA_CONF_FILE="eth_common.conf;eth_link_board_eth.conf" \
#     -DDTC_OVERLAY_FILE=link_board_eth.overlay
#

# Phytec eth shield:
# driver: zephyr/drivers/ethernet/eth_enc424j600.c
CONFIG_ETH_ENC424J600=y
CONFIG_ETH_ENC424J600_RX_THREAD_STACK_SIZE=3072
CONFIG_ETH_ENC424J600_RX_THREAD_PRIO=15
