CONFIG_NRF_CLOUD_REST=y
#CONFIG_DNS_SERVER1="2600:9000:5300:af00::1"

CONFIG_NRF_CLOUD_CREDENTIALS_MGMT_MODEM=n
CONFIG_MODEM_KEY_MGMT=n
CONFIG_MODEM_JWT=n
CONFIG_MODEM_INFO_ADD_DATE_TIME=n
CONFIG_MODEM_INFO_ADD_SIM=n
CONFIG_MODEM_INFO_ADD_SIM_ICCID=n
CONFIG_MODEM_INFO_ADD_SIM_IMSI=n

#CONFIG_MODEM_JWT=y
CONFIG_DATE_TIME=y
CONFIG_NRF_CLOUD_JWT_SOURCE_CUSTOM=y
CONFIG_NRF_CLOUD_REST_AUTOGEN_JWT=y

CONFIG_NRF_CLOUD_MQTT=n
CONFIG_NRF_CLOUD_COAP=n

CONFIG_DESH_CLOUD_REST=y
CONFIG_REST_CLIENT_SCKT_TLS_SESSION_CACHE_IN_USE=n

CONFIG_NRF_CLOUD_LOG_LEVEL_DBG=y
CONFIG_REST_CLIENT_LOG_LEVEL_DBG=y