#1st, disable all unneeded
CONFIG_MDNS_RESOLVER=n
CONFIG_MDNS_RESPONDER=n
CONFIG_MDNS_RESPONDER_DNS_SD=n
#CONFIG_DNS_SD=n #TODO: addvertise services
#CONFIG_MDNS_RESPONDER_DNS_SD=n
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=1024

#We are not using kernel heap with iperf3
CONFIG_HEAP_MEM_POOL_SIZE=1024

#not writing certs with this image
CONFIG_SHELL_CMD_BUFF_SIZE=512
CONFIG_DESH_NATIVE_TLS=n
CONFIG_DESH_AT_CMD_MODE=n

#Not testing with many children
CONFIG_DECT_NRP_MAC_CLUSTER_MAX_CHILD_ASSOCIATION_COUNT=5
CONFIG_NET_IPV6_MAX_NEIGHBORS=5

CONFIG_DECT_NRP_MAC_NRF_TX_FLOW_CTRL_BASED_ON_MDM_TX_DLC_REQS=y
# We need to enable ipv4 for iperf3 server
CONFIG_NET_IPV4=y

# Disable IP address validation checks for performance
CONFIG_NET_IP_ADDR_CHECK=n

#########
CONFIG_POSIX_API=y
CONFIG_ZVFS_OPEN_MAX=15
# Need to be the same as MAX_FDS
CONFIG_NET_SOCKETS_POLL_MAX=15
CONFIG_NET_MAX_CONTEXTS=15

CONFIG_NEWLIB_LIBC=y
CONFIG_CJSON_LIB=y
CONFIG_MINIMAL_LIBC=n
CONFIG_NEWLIB_LIBC_FLOAT_SCANF=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_FPU=y

CONFIG_DESH_IPERF3=y
CONFIG_NRF_IPERF3_RESULTS_WAIT_TIME=180
CONFIG_NRF_IPERF3_NONBLOCKING_CLIENT_CHANGES=n
CONFIG_NRF_IPERF3_HOST_NAME="nrf9151-dect-nr+-common config"

CONFIG_NET_IPV6=y

CONFIG_NET_TCP=y
CONFIG_NET_TCP_WORKQ_STACK_SIZE=2048
CONFIG_NET_TCP_INIT_RETRANSMISSION_TIMEOUT=6000
CONFIG_NET_TCP_RETRY_COUNT=6

#Following selects MBEDTLS_MAC_MD5_ENABLED that needs bunch of other features
CONFIG_NET_TCP_ISN_RFC6528=n

# Network buffers
CONFIG_NET_BUF=y
CONFIG_NET_BUF_DATA_SIZE=128
CONFIG_NET_BUF_POOL_USAGE=y

CONFIG_NET_TC_RX_COUNT=0

# Network driver config
#CONFIG_NET_DRIVERS=y

#CONFIG_NET_LOG=y
#CONFIG_NET_TCP_LOG_LEVEL_DBG=y
#CONFIG_NET_PKT_LOG_LEVEL_DBG=y

#CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
#CONFIG_NET_CONTEXT_LOG_LEVEL_DBG=y

#CONFIG_LOG_MODE_IMMEDIATE=y
