CONFIG_NRF_IPERF3_HOST_NAME="nrf9151-dect-nr+-RX-config"

CONFIG_NRF_MODEM_LIB_SHMEM_RX_SIZE=32768
CONFIG_NRF_MODEM_LIB_SHMEM_TX_SIZE=6144

CONFIG_NET_PKT_RX_COUNT=175
CONFIG_NET_BUF_RX_COUNT=350

CONFIG_NET_PKT_TX_COUNT=30
CONFIG_NET_BUF_TX_COUNT=60

CONFIG_NET_TCP_RECV_QUEUE_TIMEOUT=10000
# 1280 MTU
#CONFIG_NET_BUF_DATA_SIZE=1280

# Use variable data size to reduce memory usage for small data packets?
#CONFIG_NET_BUF_VARIABLE_DATA_SIZE=y

#CONFIG_NET_PKT_TX_COUNT=10
#CONFIG_NET_BUF_TX_COUNT=10

#CONFIG_NET_PKT_RX_COUNT=40
#CONFIG_NET_BUF_RX_COUNT=40